[[battery.display]]  # "bold red" style and discharging_symbol when capacity is between 0% and 10%
threshold = 10
style = "bold red"

[[battery.display]]  # "bold yellow" style and ðŸ’¦ symbol when capacity is between 10% and 30%
threshold = 30
style = "bold yellow"
discharging_symbol = "ðŸ’¦"

[time]
format = "[ï€—( $time )]($style)"
time_format = "%T"
